#!/bin/bash

#PBS -N lh_submit_fates
#PBS -q develop
#PBS -l select=1:mem=1G
#PBS -l walltime=5:00:00
#PBS -A P93300041
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M afoster@ucar.edu

conf=/glade/work/afoster/FATES_calibration/config_files/fates_sp_lh_gs0.config

/glade/work/afoster/FATES_calibration/CLM5PPE/jobscripts/run_ens_fates.sh ${conf}
