#!/bin/bash

#PBS -N oaat_submit_clm
#PBS -q develop
#PBS -l select=1:mem=1G
#PBS -l walltime=5:00:00
#PBS -A P08010000
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M afoster@ucar.edu

conf=/glade/work/afoster/FATES_calibration/config_files/ctsm_sp_oaat_btran.config

/glade/work/afoster/FATES_calibration/CLM5PPE/jobscripts/run_ens.sh ${conf}
