'not_vegetated': [0]
'needleleaf_evergreen_temperate_tree': [2]
'needleleaf_evergreen_boreal_tree': [2]
'needleleaf_deciduous_boreal_tree': [3]
'broadleaf_evergreen_tropical_tree': [1]
'broadleaf_evergreen_temperate_tree': [4]
'broadleaf_deciduous_tropical_tree': [5]
'broadleaf_deciduous_temperate_tree': [6]
'broadleaf_deciduous_boreal_tree': [6]
'broadleaf_evergreen_shrub': [7]
'broadleaf_deciduous_temperate_shrub': [9]
'broadleaf_deciduous_boreal_shrub': [10, 11]
'c3_arctic_grass': [12]
'c3_non-arctic_grass': [13]
'c4_grass': [14]
'c3_crop': [15]
'c3_irrigated': [16]