not_vegetated: [0]
broadleaf_evergreen_tropical_tree: [4]
needleleaf_evergreen_extratrop_tree: [1, 2]
needleleaf_colddecid_extratrop_tree: [3]
broadleaf_evergreen_extratrop_tree: [5]
broadleaf_hydrodecid_tropical_tree: [6]
broadleaf_colddecid_extratrop_tree: [7, 8]
broadleaf_evergreen_extratrop_shrub: [9]
broadleaf_hydrodecid_extratrop_shrub: []
broadleaf_colddecid_extratrop_shrub: [10]
broadleaf_evergreen_arctic_shrub: [11]
broadleaf_colddecid_arctic_shrub: [11]
arctic_c3_grass: [12]
cool_c3_grass: [13]
c4_grass: [14]
c3_crop: [15]
c3_irrigated: [16]
