#!/bin/bash

#PBS -N submit_ensemble
#PBS -q develop
#PBS -l select=1:mem=1G
#PBS -l walltime=5:00:00
#PBS -A P08010000
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M afoster@ucar.edu

RUN_ENSEMBLE_SCRIPT="/glade/work/afoster/FATES_calibration/fates_calibration_library/scripts/run_ensemble"

# ------------------ #
# Check config input #
# ------------------ #

if [[ -z "${CONF:-}" ]]; then
  echo "Error: CONF variable not set. Use: qsub -v CONF=/path/to/config submit_oaat"
  exit 1
fi

echo "Using config: $CONF"

# ------------------ #
# Submit ensemble    #
# ------------------ #

"$RUN_ENSEMBLE_SCRIPT" "$CONF"
